openapi: 3.0.0
info:
  title: Todo API
  description: REST API for managing Todos.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local server

paths:
  /api/todos:
    get:
      summary: Retrieve all todos
      description: Returns a list of todos.
      responses:
        '200':
          description: A JSON array of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      description: Adds a new todo to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Todo created successfully
        '400':
          description: Invalid input

  /api/todos/{id}:
    put:
      summary: Update an existing todo
      description: Updates a todo based on its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Todo updated successfully
        '404':
          description: Todo not found
    delete:
      summary: Delete a todo
      description: Deletes a todo based on its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo deleted successfully
        '404':
          description: Todo not found


components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Buy groceries
        deadline:
          type: string
          format: date
          example: 2024-12-31
        isCompleted:
          type: boolean
          example: false
